prod_params = {
    "base_url": "https://localhost:25734",
    "user": "admin",
    "password": ""
}

dev_params = {
    "base_url": "https://localhost:18724",
    "user": "admin",
    "password": ""
}

CUSTOMERS = [
    "The Drink Spot",
    "Thirst Quencher Co.",
    "Brews and More",
    "Beverage Express",
    "Refreshment Central",
    "Liquid Delights",
    "Drink Oasis",
    "The Beverage Stop",
    "Sip and Savor",
    "Drink Haven",
    "The Liquid Lounge",
    "Quench King",
    "Drinkville",
    "Thirsty Tiger",
    "The Beverage Barn",
    "The Liquid Loft",
    "Drink Dynasty",
    "Refreshment Rendezvous",
    "Sip Solutions",
    "Drink Daze",
    "The Beverage Bazaar",
    "Liquid Love",
    "Thirst Tamer",
    "Drink Depot",
    "Sip Sensations",
    "The Beverage Brigade",
    "The Liquid Lounge",
    "Refreshment Resort",
    "Drink Dynasty",
    "Thirsty Travels",
    "Beverage Boutique",
    "Liquid Land",
    "Drink Delights",
    "Sip Spot",
    "The Beverage Blast",
    "Thirst Trap",
    "Drink Emporium",
    "Refreshment Retreat",
    "Liquid Libations",
    "Sip and Savor",
    "The Beverage Bistro",
    "Drink Destination",
    "Thirsty Trails",
    "Beverage Bonanza",
    "Liquid Luxury",
    "Drink District",
    "Refreshment Royale",
    "Sip Station",
    "The Beverage Hub",
    "Thirst Quenchers",
    "Drink Den",
    "Liquid Lagoon",
    "Refreshment Revive",
    "Sip Savvy",
    "The Beverage Binge",
    "Drink Drive",
    "Thirsty Times",
    "Beverage Bliss",
    "Liquid Legend",
    "Drink Delight",
    "Refreshment Republic",
    "Sip Supreme",
    "The Beverage Buzz",
    "Drink Desire",
    "Thirst Quencher Zone",
    "Beverage Boulevard",
    "Liquid Lounge",
    "Drink Drift",
    "Refreshment Runway",
    "Sip and Chill",
    "The Beverage Bonanza",
    "Thirsty Thrills",
    "Drink Dream",
    "Liquid Landmark",
    "Refreshment Retreat",
    "Sip Select",
    "The Beverage Bazaar",
    "Drink District",
    "Thirsty Trails",
    "Beverage Bliss",
    "Liquid Luxe",
    "Drink Depot",
    "Refreshment Rendezvous",
    "Sip Solutions",
    "The Beverage Brigade",
    "Thirsty Tiger",
    "Drink Dynasty",
    "Liquid Love",
    "Refreshment Resort",
    "Sip and Savor",
    "The Beverage Blast",
    "Drink Daze",
    "Thirst Tamer",
    "Beverage Boutique",
    "Liquid Land",
    "Refreshment Revive",
    "Sip Spot",
    "The Beverage Bistro",
    "Drink Destination",
    "Thirsty Travels",
    "Liquid Lounge",
    "Drink Delights",
    "Sip Sensations",
    "The Beverage Binge",
    "Refreshment Royale",
    "Thirst Trap",
    "Drink Emporium",
    "Liquid Libations",
    "Sip Savvy",
    "The Beverage Hub",
    "Refreshment Retreat",
    "Drink District",
    "Thirst Quenchers",
    "Liquid Lagoon",
    "Sip and Savor",
    "The Beverage Haven",
    "Drinkville",
    "Refreshment Central",
    "Thirst Quencher Co.",
    "Liquid Delights",
    "Sip Solutions",
    "The Brew Bear",
    "The Drink Spot",
    "Beverage Express",
    "Brews and More",
    "Thirsty Avenue",
    "Drink Oasis",
    "The Beverage Stop",
    "Liquid Lounge",
    "Quench Queen",
    "Drink Haven",
    "Refreshment Junction",
    "Sip and Smile",
    "Thirsty Delights",
    "The Beverage Barn",
    "The Liquid Depot",
    "Drink Dynasty",
    "Refreshment Oasis",
    "Sip Solutions",
    "Drink Central",
    "The Thirsty Tiger",
    "Beverage Boulevard",
    "Liquid Landmark",
    "Drink Delights",
    "Sip Spot",
    "The Beverage Bazaar",
    "Thirst Quencher Zone",
    "Drinkville Delights",
    "Refreshment Resort",
    "Liquid Luxury"
]
